### ISSUE TITLE
Support for @NotNull in Groovy Lang

### ISSUE THREAD

**Issue by utenma** [JetBrains/java-annotations#110]
Currently the annotation it's ignored on groovy, can only be enabled for Java

![image](https://github.com/user-attachments/assets/807a381c-7b88-4b0d-a93d-344a4507c2cf)

**Comment by amaembo** [comment]
This repository is about declaring the annotations and defining their semantics. Support of these annotations in particular tools (such as IntelliJ IDEA) is out of scope here. Please report your issues to youtrack.jetbrains.com.
