### ISSUE TITLE
Allow `@Language("regexp") CharSequence regex`

### ISSUE THREAD

**Issue by xkr47** [JetBrains/java-annotations#16]
Where should report (if not here) that IntelliJ IDEA reports an error when using
```java
@Language("regexp") CharSequence regex
```
while there are libraries (like AssertJ) that allow specifying regexps as `CharSequence`s for convenience? My request is thus to allow @Language annotations for `CharSequence` type variables in addition to `String`.

**Comment by xkr47** [comment]
I have now filed it here: https://youtrack.jetbrains.net/issue/IDEA-221169

**Comment by amaembo** [comment]
Yes, IDEA issues should be filed in YouTrack. Thanks.
