### ISSUE TITLE
Add an @Experimental annotation

### ISSUE THREAD

**Issue by burdoto** [JetBrains/java-annotations#17]
Just had a small idea;
what about an `@Experimental` annotation for methods and fields which would let a user somehow know that the method they are trying to use is experimental and might not work correctly?

**Comment by chashnikov** [comment]
We already have such annotation in IntelliJ project sources. It makes sense to move it (along with other annotations) to this library. I've filed an issue about that in IDEA's issue tracker: [IDEA-224840](https://youtrack.jetbrains.com/issue/IDEA-224840).

**Comment by chashnikov** [comment]
We have published version 18.0.0 which includes `ApiStatus.Experimental` annotation. Note that its meaning is slightly different from that you want, it indicates status of API, not quality of its implementation. But if an implementation is experimental this also means that API is experimental as well, so you can use the annotation and specify additional details in javadoc.

**Comment by burdoto** [comment]
Great, thanks! Now I'm responsible for versions 17 and 18, its awesome how you guys work.
