### ISSUE TITLE
What about @ParametersAreNonnullByDefault?

### ISSUE THREAD

**Issue by bibarsov** [JetBrains/java-annotations#18]
I think it's a great replacement for jsr-305's annotations (in the context of IntellijIdea's inspection). Would Jetbrains support that annotation?

**Comment by bibarsov** [comment]
The same question for @ParametersAreNullableByDefault

**Comment by amaembo** [comment]
For now, we are not planning to add them.

**Comment by matheusstutzel** [comment]
@amaembo any updates on this?

**Comment by Sxtanna** [comment]
Sorry but... there are existing semantics for this across several implementations of this annotation within this scope. There is precedent for this, it's really **not** MUCH more complex, as mentioned in #6 by @amaembo. 

Please just make it work how other annotations have worked, for several years.

**Comment by CC007** [comment]
I found this page: https://www.jetbrains.com/help/idea/parametersarenonnullbydefault-annotation.html

Does that mean it is supported now?

**Comment by overheadhunter** [comment]
> Does that mean it is supported now?

No, not without said dependency which causes split packages:

> To use the annotation, add the `jsr305` library to module dependencies

**Comment by alexei-osipov** [comment]
If there no plans to add equivalent `@ParametersAreNonnullByDefault` could you please provide a recommendation on what should be used instead. Obviously, JSR 305 can't be used because of deprecation and split package problem since Java 9.

**Comment by amaembo** [comment]
NotNullByDefault is added in 26.0.0
https://javadoc.io/static/org.jetbrains/annotations/26.0.0/org/jetbrains/annotations/NotNullByDefault.html

**Comment by matheusstutzel** [comment]
@amaembo are there any plans to add `NullableByDefault` as well?

**Comment by amaembo** [comment]
@matheusstutzel no, it's unnecessary.

**Comment by CC007** [comment]
> @matheusstutzel no, it's unnecessary.

Is it unnecessary? What if you want notnull by default in `some.package`, but you want nullable by default in `some.package.subpackage` specifically? Or nullable  by default in a certain class that's in a notnull package?

**Comment by amaembo** [comment]
There's no such thing as sub-packages in Java. The annotation doesn't affect any packages other than the package where it's declared. 

Having Nullable by default is a rare choice, as most of the APIs are notnull. Also, and complex annotation hierarchy could be confusing for API users. It's better to annotate Nullable methods explicitly, or not using NotNullByDefault at all. Alternative, you can annotate every class with NotNullByDefault, except those classes where Nullable APIs prevail.

**Comment by CC007** [comment]
Does NotNullByDefault support annotating modules, so the whole module is notnull by default?

**Comment by amaembo** [comment]
Not yet, though we are considering this.

**Comment by amaembo** [comment]
This is not a good idea. Packages with the same prefix could be a part of another artefact, which is completely unaware of your annotation. This problem should be solved with module-level annotation.

**Comment by CC007** [comment]
> This is not a good idea. Packages with the same prefix could be a part of another artefact, which is completely unaware of your annotation. This problem should be solved with module-level annotation.

I created an issue for the module-level support for this annotation.

Other than that, I agree that you don't want to willy nilly apply the annotation to packages with the same prefix in another module. I do believe it could be possible to only cascade down to the subpackages within the current module though. That way you would avoid that side effect.
