### ISSUE TITLE
Support runtime policy

### ISSUE THREAD

**Issue by dzikoysk** [JetBrains/java-annotations#23]
Is there any chance to support runtime policy by JetBrains annotations? As you can see `javax.annotations` are available at runtime:

https://github.com/amaembo/jsr-305/blob/d7734b13c61492982784560ed5b4f4bd6cf9bb2c/ri/src/main/java/javax/annotation/Nullable.java#L28

It's just really helpful in various tooling utilities.

**Comment by amaembo** [comment]
Duplicate of #1.
