### ISSUE TITLE
@RegExp 's prefix() and suffix() not working in IDEA 2020.1

### ISSUE THREAD

**Issue by moonfruit** [JetBrains/java-annotations#25]
[@RegExp](https://github.com/JetBrains/java-annotations/blob/master/common/src/main/java/org/intellij/lang/annotations/RegExp.java)'s prefix() and suffix() not worked as [@Language](https://github.com/JetBrains/java-annotations/blob/master/common/src/main/java/org/intellij/lang/annotations/Language.java)

For example:
![image](https://user-images.githubusercontent.com/1070090/85108259-fe763700-b241-11ea-9816-3a8cb24e56e9.png)

**Comment by BasLeijdekkers** [comment]
Please file an issue at https://youtrack.jetbrains.com/issues/IDEA and include sample code in text form.

**Comment by amaembo** [comment]
Agreed with Bas. This issue tracker tracks the issues in the annotations package itself, not in the interpretation of these annotations in IDEs.
