### ISSUE TITLE
`@NotNull` throws NPE instead of IllegalArgumentException as comments mention

### ISSUE THREAD

**Issue by mashimom** [JetBrains/java-annotations#27]
Hello,

I added the library to a SpringBoot 2.x Java 14 project and my tests fail on the wrong exception being thrown from the annotated code.

Could you please confirm the problem from a minimal Java 8 case at https://github.com/mashimom/min_case_annotations

The comments on the Annotation code state that it should default to IllegalArgumentException.

Thank you,
Marco

**Comment by amaembo** [comment]
I believe, your question is answered here:
https://stackoverflow.com/a/48682792/4856258
