### ISSUE TITLE
Is it vaild for Kotlin?

### ISSUE THREAD

**Issue by cpdyj** [JetBrains/java-annotations#28]
I use `@RegExp` as the following pattern. But looks it not working.
```kotlin
fun f(@RegExp r: String){}
```

**Comment by cpdyj** [comment]
Problem resolved. Use `@Language("RegExp")` instead. But is it a bug? Thank you

**Comment by amaembo** [comment]
Probably this should be reported to [Kotlin plugin issue tracker](https://youtrack.jetbrains.com/issues/KT).
