### ISSUE TITLE
Releases for 20.0.0 and 20.1.0 are missing on GH

### ISSUE THREAD

**Issue by marandaneto** [JetBrains/java-annotations#32]
The tags are created, libs are published, but releases are missing on GH:
https://github.com/JetBrains/java-annotations/releases

**Comment by amaembo** [comment]
Fixed, thanks.

**Comment by marandaneto** [comment]
that was fast, thanks!

**Comment by Stephan202** [comment]
@amaembo it looks like the tag for 24.0.1 is also missing. :eyes:

**Comment by amaembo** [comment]
Thanks, will update
