### ISSUE TITLE
Annotations are shown multiple time in javadocs

### ISSUE THREAD

**Issue by original-codematrix** [JetBrains/java-annotations#35]
I'm using this dependency:
```xml
<dependency>
    <groupId>org.jetbrains</groupId>
    <artifactId>annotations</artifactId>
    <version>20.1.0</version>
</dependency>
```
With this maven plugin:
```xml
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-javadoc-plugin</artifactId>
    <version>3.2.0</version>
    <executions>
        <execution>
            <id>attach-javadocs</id>
            <phase>deploy</phase>
            <configuration>
                <quiet>true</quiet>
                <notimestamp>true</notimestamp>
                <encoding>${utf.encoding}</encoding> <!-- utf.encoding = UTF-8 -->
                <docencoding>${utf.encoding}</docencoding>
                <charset>${utf.encoding}</charset>
                <additionalOptions>
                    <additionalOption>-XDignore.symbol.file</additionalOption>
                    <additionalOption>-Xdoclint:-html</additionalOption>
                </additionalOptions>
                <linksource>true</linksource>
                <source>${java.version}</source> <!-- java.version = 11 -->
            </configuration>
            <goals>
                <goal>jar</goal>
            </goals>
        </execution>
    </executions>
</plugin>
```

When I now create a Javadoc of a class that contains e. g. `NotNull` or `Nullable` it results looks like this in the JavaDocs:

**All methods overview:**
![image](https://user-images.githubusercontent.com/7052666/95109045-57f46a00-073c-11eb-9685-4f4635899733.png)
![image](https://user-images.githubusercontent.com/7052666/95109377-d18c5800-073c-11eb-8d03-00f6a96d4200.png)

**Method detail:**
![image](https://user-images.githubusercontent.com/7052666/95109108-6a6ea380-073c-11eb-846c-60ad9fdc92b1.png)
![image](https://user-images.githubusercontent.com/7052666/95109421-dd781a00-073c-11eb-9bbd-34c297ab1709.png)

I've also switched to another annotation library (jsr305) from that these annotations are only shown once.

**Comment by amaembo** [comment]
This is not the annotation package bug. This is how javadoc tool works when the annotation has multiple targets including TYPE_USE. E.g. for a class like this:

```java
import java.lang.annotation.*;

@Documented
@Target({ElementType.TYPE_USE, ElementType.METHOD})
public @interface Test {
  @Test String value() default "";
}
```

Generating javadoc (simply by invoking `javadoc Test.java`) you will see duplicated annotation:

```java
@Test
@Test java.lang.String value
```

You may consider [reporting an issue](https://bugreport.java.com/bugreport/) to OpenJDK

JSR-305 works because it doesn't provide TYPE_USE target. You may use our annotations-java5 package as an alternativem it should work as well.
