### ISSUE TITLE
ApiStatus and Debug should contain private throwing constructor

### ISSUE THREAD

**Issue by JarvisCraft** [JetBrains/java-annotations#38]
While class `ApiStatus` and `Debug` simply server a purpose of being a common namespace for multiple annotations and cannot be extended ...
https://github.com/JetBrains/java-annotations/blob/d7c469b3b53c2135ba1c8863fc5eb2f5d5ccb36c/common/src/main/java/org/jetbrains/annotations/ApiStatus.java#L25
https://github.com/JetBrains/java-annotations/blob/d7c469b3b53c2135ba1c8863fc5eb2f5d5ccb36c/common/src/main/java/org/jetbrains/annotations/Debug.java#L28
... they still can be instantiated which should be explicitly prohibited by adding a private constructor throwing an exception.

I am ready to open a fixing PR.

**Comment by amaembo** [comment]
Sounds reasonable. Please file a PR.

**Comment by JarvisCraft** [comment]
#39 has been created to implement these changes
