### ISSUE TITLE
Improvement: Provide a Java Module distribution for JetBrains annotations on Maven Central

### ISSUE THREAD

**Issue by marcelbaumann** [JetBrains/java-annotations#47]
I greatly appreciate that the annotations package is providing an _Automatic-Module-Name_ definition.
The current version of JDK 16 still create warnings when using an automatic module with statements such as 
_requires static transitive org.jetbrains.annotations;_

Java 9 was released in September 2017 and JDK 17 is around the corner.
I would assume it is time that JetBrains as a leading technology company finally release an annotation package which really supports the Java module concept in maven central.

You have already the module-info.java file, you just need to release a version containing it on Maven Central. And it is really time, Java 11 and Java 17 are LTS versions.

I am trying to move my java applications to a modular structure and I have to invest quite an effort to find a way around various packages still created for JDK 9-- meaning for DK versions older than 4 years.

Sincerely

**Comment by amaembo** [comment]
It's already implemented in master (see e1f9f35d61521652abcb65d29cd3637ed4a344a1). We are still solving some infrastructure problems due to BinTray end-of-life. When we solve them we will release a new version.

**Comment by amaembo** [comment]
21.0.0 with module-info released today. Please test whether it works for you.
