### ISSUE TITLE
@Language("SpEL") support custom class of rootObject to resolve methods and fields?

### ISSUE THREAD

**Issue by timandy** [JetBrains/java-annotations#56]
I use @Language("SpEL")  on Annotation field, idea auto inject spel on the field. But it can't resolve methos. I want to know is there a way to custom the rootObject of SpEL injections. ps: The build in injections like @PreAuthorize can resolve methods.

**Comment by amaembo** [comment]
Hello! This repository is about annotation specification. If you want to report issues about their behavior in JetBrains IDEs, please use https://youtrack.jetbrains.com/ Thanks!

**Comment by timandy** [comment]
https://youtrack.jetbrains.com/issue/IDEA-273964
