### ISSUE TITLE
@ValueType annotation in preparation for Valhalla

### ISSUE THREAD

**Issue by TheMode** [JetBrains/java-annotations#57]
A new annotation giving a warning when an instance is used as a monitor. As specified in `PrimitiveObject` documentation https://github.com/openjdk/valhalla/blob/lworld/src/java.base/share/classes/java/lang/PrimitiveObject.java#L51

It could also be used to discourage users from using the object monitor directly (in the case where it is used internally)

**Comment by amaembo** [comment]
There's already `@jdk.internal.ValueBased` annotation that is used in JDK for this purpose.

**Comment by TheMode** [comment]
As the name indicates, isn't it strictly internal?

**Comment by amaembo** [comment]
Yes, currently it is. But this may change in the future, and we don't want to repeat JDK annotation.
