### ISSUE TITLE
Add key to PGP keys map

### ISSUE THREAD

**Issue by silnith** [JetBrains/java-annotations#62]
Maven Central requires all published artifacts to be [signed using PGP](https://maven.apache.org/repository/guide-central-repository-upload.html#pgp-signature). If a publisher provides their key ID to [PGP keys map](https://github.com/s4u/pgp-keys-map) then end users can use the [Verify PGP signatures plugin](https://github.com/s4u/pgpverify-maven-plugin) to validate that the artifact has not been altered or replaced as part of a supply-chain attack.

**Comment by vlsi** [comment]
@silnith , what do you think of https://www.sigstore.dev/ ?

**Comment by ao-apps** [comment]
This issue may be closed.  We've submitted a PR to the pgp-keys-map project covering this already.  This java-annotations project has published their PGP key, which is sufficient for positive identification: https://github.com/s4u/pgp-keys-map/pull/688
