### ISSUE TITLE
Please publish the official PGP keys so the releases can be verified

### ISSUE THREAD

**Issue by vlsi** [JetBrains/java-annotations#63]
See https://youtrack.jetbrains.com/issue/KT-33781
See https://github.com/junit-team/junit5/issues/2020

I get the following error when upgrading to 23.0:

```
Checksum/PGP violations detected on resolving configuration :src:core:compileClasspath
Trusted PGP keys for group org.jetbrains are [bcf4173966770193, 379ce192d401ab61],
however artifact is signed by [c2148900bcd3c2af] only:
org.jetbrains:annotations:23.0.0 (pgp=[c2148900bcd3c2af], sha512=[computation skipped])
```

Note: this is different from https://github.com/JetBrains/java-annotations/issues/62, and what I want is a reference of the official PGP key(s) on the project website (or at GitHub).

**Comment by amaembo** [comment]
Committed to the repo root. Btw it's also available here: https://download.jetbrains.com/KEYS

**Comment by vlsi** [comment]
Nice, thank you.
It would be great to have a link as well near `Using the annotations` section or a PGP badge.

**Comment by amaembo** [comment]
> It would be great to have a link as well near Using the annotations section or a PGP badge.

PR is welcome :-)

**Comment by ao-apps** [comment]
Thank you for adding the key.  We have added this information to the [PGP Keys Map](https://github.com/s4u/pgp-keys-map) project supported by @s4u.  They provide a Maven plugin that [verifies PGP keys](https://github.com/s4u/pgpverify-maven-plugin) during builds.

https://github.com/s4u/pgp-keys-map/pull/688
