### ISSUE TITLE
@HiddenFromAutocomplete or the most useful missing low hanging fruit

### ISSUE THREAD

**Issue by LifeIsStrange** [JetBrains/java-annotations#64]
Hi @Jetbrains, there are many cases where a method has been superseded by another or simply exists for an implementationDetail reason.
E.g in Kotlin multiplatform in order to make lists much more interoperable between pure JS and Kotlin JVM code, I have to make an extension method on MutableLIst.addAllMPP() that only exists as an implementation detail, it is used in our Kotlin JS and JVM wrappers of arraylists but elsewhere we want developpers to only use the regular .addAll().
There is already the @Deprecated annotation which put a strikethrough on the autocomplete result, but here we want to remove all noise and simply hides the method from autocomplete results, a basic filter.
Therefore it would be amazing if you could implement an identifier annotation @HiddenFromAutocomplete that the Kotlin plugin (and maybe the Java one) could leverage :)
On a more common case, it could be used for accelerating the reduction of use of the most evil deprecated or dangerous functions. 

@amaembo friendly ping

**Comment by amaembo** [comment]
I'm not sure you can add this library as a dependency on a Kotlin multiplatform project, as this library is written in Java.

If it's implementation detail why not declare it as `internal`?

**Comment by chashnikov** [comment]
Also note that there is an attribute `level` in `@Deprecated` annotation in Kotlin, and specifying `DeprecationLevel.HIDDEN` will hide the variant from autocompletion as well.

**Comment by LifeIsStrange** [comment]
> I'm not sure you can add this library as a dependency on a Kotlin multiplatform project, as this library is written in Java.
Yeah good question but I wanted at least to signal the use case to JetBrains.

> If it's implementation detail why not declare it as internal?
It's a top level extension method, my BD ArrayList in kotlin js and the one in jvm are not on the same packages and needs a top level for both if them to have access to it. Internal make it unreachable.

@chashnikov 
> specifying DeprecationLevel.HIDDEN will hide the variant from autocompletion as well
Well that would solve my issue unfortunately it does not seem to work.
I have put this label and even after restarting the IDE, list._addAllMPP still shows in autocomplete :/

**Comment by chashnikov** [comment]
Yes, `DeprecationLevel.HIDDEN` is the most strict deprecation level, so code which use it won't compile. I think if it's ok to use the function from some trusted places, it shouldn't be marked as deprecated (which means that it shouldn't be used at all), it's better to somehow mark it as 'internal'. We already have `@ApiStatus.Internal` annotation in this library exactly for the cases where it isn't possible to limit visibility using visibility modifiers, and IDEA will show a warning if such items are used from external code. Currently this annotation isn't taken into account by completion, but I think it makes sense to assign lower priority for such items ([IDEA-285531](https://youtrack.jetbrains.com/issue/IDEA-285531)).

Anyway, I don't think we should remove any items from the completion list if code which use these items compiles successfully. If some item isn't shown in the completion, but users will be able to type it manually and get code which works, they'll think that it's a bug in the IDE. I think it should be enough to move such items to the bottom of the completion list and highlight them in a special way directly in the completion popup.
