### ISSUE TITLE
Missing explanation in javadocs

### ISSUE THREAD

**Issue by liry** [JetBrains/java-annotations#84]
E.g. in [NotNull.html#exception()](https://javadoc.io/static/org.jetbrains/annotations/24.0.0/org/jetbrains/annotations/NotNull.html#exception()) there's a description about some exceptions that can be thrown in runtime, but I found no description how it actually works. The readme states only "serve as an additional documentation and can be interpreted by IDEs and static analysis tools to improve code analysis". I guess it's some magic in IntelliJ, but haven't found it in it's [docs](https://www.jetbrains.com/help/idea/annotating-source-code.html) either.
But when I build the code in IntelliJ, it somehow magically adds runtime checks:
```
java.lang.IllegalStateException: @NotNull method com/MyClass.myMethod must not return null
  at com.MyClass.$$$reportNull$$$0(MyClass.java)
  at com.MyClass.myMethod(MyClass.java:108)
```
I'd like to read some docs how it works and if I can also e.g. add runtime checks into build outside IntelliJ.

**Comment by amaembo** [comment]
There's an option in IntelliJ IDEA to control this, called "Add runtime assertions for not-null annotated methods and parameters". You can find some information in [IntelliJ IDEA help](https://www.jetbrains.com/help/idea/2022.3/compiler.html). Basically, it's an annotation processor. This package intentionally avoids specifying IntelliJ IDEA implementation details, as other clients (static analyzers, IDEs, annotation processors) may use this information in another way.
