### ISSUE TITLE
JPMS/Modular support

### ISSUE THREAD

**Issue by nbrugger-tgm** [JetBrains/java-annotations#90]
Since you have no dependencies on basically anything, jpms support would be easy to implement and help adoption

**Comment by amaembo** [comment]
But it's already adapted to JPMS. The module name is `org.jetbrains.annotations`. It's even listed here:
https://github.com/sormuras/modules/blob/main/doc/Top1000-2022.txt.md
Does anything work incorrectly for you?

**Comment by nbrugger-tgm** [comment]
1, Holy F* that awas fast
2. I see you are right - an dependency of mine transitively included version 13 which has no support and it messed with the modulepath - sorry for the wrong issue
