### ISSUE TITLE
When will CheckReturnValue be promoted to stable?

### ISSUE THREAD

**Issue by SgtSilvio** [JetBrains/java-annotations#94]
`@CheckReturnValue` was added 10 month ago and is still experimental (https://github.com/JetBrains/java-annotations/blob/e575d984fb998b5bf5d42b6d68c87242e771addd/common/src/main/java/org/jetbrains/annotations/CheckReturnValue.java#L33).
Is there any timeline when it will be promoted to stable?

**Comment by amaembo** [comment]
Thank you for reminder, let's do this
