### ISSUE TITLE
CodeQL reporting insecure usage of http

### ISSUE THREAD

**Issue by eygraber** [JetBrains/java-annotations#95]
https://github.com/eygraber/portal/security/code-scanning/2

> Downloading or uploading artifacts over insecure protocol (eg. http or ftp) to/from repository http://oss.sonatype.org/service/local/staging/deploy/maven2/

From `.gradle/expanded/zip_72ac29dee68b63d11710f49a42861308/META-INF/maven/org.jetbrains/annotations/pom.xml:129 `

**Comment by amaembo** [comment]
Hello! Are you a robot or a human? The message looks automated. Could you explain precisely what is the problem, and ideally send a pull-request to fix it?

**Comment by eygraber** [comment]
I am a human. Codeql is a security tool for GitHub, and it found that this library's POM is using http for a repository instead of https.

**Comment by amaembo** [comment]
@eygraber we don't have pom.xml in our repository. We use Gradle. I failed to find any "http://" substrings in our source code. It would be nice if you point exactly to the problematic place in the sources, which, in your opinion, requires fixing. Thank you.

**Comment by chashnikov** [comment]
Well, actually pom.xml for artifacts is generated by Gradle scripts, and we did have `http://` string there in the past, but as far as I can see such problems are already fixed (see [this commit](https://github.com/JetBrains/java-annotations/commit/984b59d74a2bd1a47392a78f22d8187562574fea), for example). Moreover, the latest version of [pom.xml at Maven Central](https://repo.maven.apache.org/maven2/org/jetbrains/annotations/24.1.0/annotations-24.1.0.pom) has less than 129 lines, so could you please tell us which version do you use?

**Comment by eygraber** [comment]
It's version 23.0.0 but it looks like it's related to a transitive dependency. I'll investigate more, and reopen if needed. Thanks
